"""170 — Funding semantics audit (censoring / structure modes).

Read-only. Scans binance_free_db history/funding, marks capped observations,
writes reports/funding_semantics_audit.md + csv summary.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from harness.lib.funding_semantics import (  # noqa: E402
    annotate_series,
    censor_summary,
    load_binance_funding_parquet,
    load_measurement_config,
)

FUNDING_DIR = Path(r"C:\Users\10639\Desktop\加密\binance_free_db\history\funding")
OUT_MD = ROOT / "reports" / "funding_semantics_audit.md"
OUT_CSV = ROOT / "reports" / "funding_semantics_audit.csv"
MAX_SYMBOLS = 70  # all available typically


def main() -> int:
    if not FUNDING_DIR.exists():
        print(f"MISSING {FUNDING_DIR}")
        return 1
    cfg = load_measurement_config()
    files = sorted(FUNDING_DIR.glob("*.parquet"))[:MAX_SYMBOLS]
    rows = []
    all_ann = []
    for fp in files:
        sym = fp.stem
        try:
            raw = load_binance_funding_parquet(fp)
            ann = annotate_series(raw["rate_decimal"], unit="decimal", cfg=cfg)
            s = censor_summary(ann)
            s["symbol"] = sym
            rows.append(s)
            ann = ann.copy()
            ann["symbol"] = sym
            all_ann.append(ann)
        except Exception as e:
            rows.append({"symbol": sym, "error": str(e), "n": 0})

    df = pd.DataFrame(rows)
    df.to_csv(OUT_CSV, index=False)

    ok = df[df.get("n", pd.Series(dtype=float)).fillna(0) > 0] if "n" in df.columns else df
    total_n = int(ok["n"].sum()) if len(ok) else 0
    total_cap = int(ok["n_capped"].sum()) if len(ok) and "n_capped" in ok.columns else 0
    total_mode = int(ok["n_structure_mode"].sum()) if len(ok) and "n_structure_mode" in ok.columns else 0

    # pooled rate extremes among capped
    cap_note = ""
    if all_ann:
        big = pd.concat(all_ann, ignore_index=True)
        capped = big[big["is_capped"]]
        if len(capped):
            cap_note = (
                f"- capped rate range: [{capped['rate_decimal'].min():.6g}, "
                f"{capped['rate_decimal'].max():.6g}]\n"
                f"- top nearest_cap modes:\n"
                f"{capped['nearest_cap'].value_counts().head(8).to_string()}\n"
            )

    worst = (
        ok.sort_values("pct_capped", ascending=False).head(10)
        if len(ok) and "pct_capped" in ok.columns
        else ok.head(0)
    )

    md = f"""# Funding Semantics Audit (170)

- date: generated by `scripts/170_funding_semantics_audit.py`
- source: `{FUNDING_DIR}`
- measurement config: `config/funding_measurement.yaml` v1
- symbols scanned: {len(files)}
- pooled n: {total_n}
- pooled capped: {total_cap} ({(total_cap / total_n * 100) if total_n else 0:.3f}%)
- pooled structure_mode: {total_mode} ({(total_mode / total_n * 100) if total_n else 0:.3f}%)

## Interpretation

1. **Capped rows** = rate near exchange hard bounds → true premium pressure is *censored* (unknown beyond cap).
2. Do **not** use capped points as OLS dependent variable or extreme-quantile training targets.
3. Cross-section z-scores across symbols remain invalid without same settlement hours + IMN depth (see StepOneAi notes in `reports/external_intel/x_quant_digest_2026-08.md`).
4. s005-style **directional** funding edges stay closed; this audit is infrastructure only.
5. s014 market-neutral carry may use uncapped rates + explicit cost; still needs own alpha_card research.

{cap_note}

## Highest censor share (top 10)

```
{worst[['symbol','n','n_capped','pct_capped','min','max']].to_string(index=False) if len(worst) else 'n/a'}
```

## CSV

`{OUT_CSV}`
"""
    OUT_MD.write_text(md, encoding="utf-8")
    print(md)
    print(f"Wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
